modLoader="javafml"
loaderVersion="[43,44)"
license="MIT"

[[mods]]
modId="reengineered_toolbox"
version="${file.jarVersion}"
displayName="ReEngineered Toolbox"
authors="DivineAspect, SkySom"
description='''Faces for days'''

[[dependencies.reengineered_toolbox]]
modId="forge"
mandatory=true #mandatory
versionRange="[43.2.0,43.3.0)"
ordering="NONE"
side="BOTH"

[[dependencies.reengineered_toolbox]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"