@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package xyz.brassgoggledcoders.reengineeredtoolbox.model;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;